---
version: "2.1"
services:
  smokeping:
    image: ghcr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /srv/d/config/smokeping/config:/config
      - /srv/d/data/smokeping/data:/data
    ports:
      - 8080:80
    restart: unless-stopped
